# coding: utf-8

"""
    vdl

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="vdl",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="v1",
)

app.include_router(DefaultApiRouter)
